Fix/checkbox
Localitos/pluto pull request #216
Opened 2022-11-13 22:54 UTC by alinurr1

## Description of the change
This PR fixes checkbox width when a long label text is provided
<img width="1268" alt="Screen Shot 2022-11-14 at 04 46 53" src="https://user-images.githubusercontent.com/39182629/201548829-780c3017-c34b-4a59-ab91-492526172d11.png">

## Testing the change

- [ ] Write your testing instructions here

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Non-Breaking Change (change to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review

- [x] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.

2022-11-14 09:06 UTC, nyan07 commented on .changeset/eleven-rice-mate.md
> +"@localyze-pluto/components": minor
It should be a patch. It is just a bug fixing.

2022-11-14 09:08 UTC, nyan07 requested changes
Please, talk with Hanna and check the designs. I think the check should be aligned to the top.

2022-11-15 13:16 UTC, nyan07 approved these changes

2022-11-15 16:15 UTC, richbachman approved these changes

2022-11-16 11:57 UTC, jvaladas approved these changes

2022-11-17 09:26 UTC, merged